import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const inventory_reception_tables: KirletTableDecl[] = [
  {
    name: "inventory_reception",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "estado", type: "text" },
      { name: "purchase_order_nombre", type: "text" },
      { name: "purchase_order_id", type: "text" },
      { name: "producto_id", type: "text" },
      { name: "proveedor_nombre", type: "text" },
      { name: "referencia", type: "text" },
      { name: "fecha_esperada", type: "text" },
      { name: "total_esperado", type: "real" },
      { name: "total_recibido", type: "real" },
      { name: "documento_tipo", type: "text" },
      { name: "documento_id", type: "text" },
      { name: "documento_nombre", type: "text" },
      { name: "cantidad", type: "real" },
      { name: "producto", type: "text" },
      { name: "producto_nombre", type: "text" },
      { name: "producto_codigo", type: "text" },
      { name: "codigo_proveedor", type: "text" },
      { name: "cantidad_esperada", type: "real" },
      { name: "cantidad_recibida", type: "real" },
      { name: "cantidad_acomodada", type: "real" },
      { name: "costo_unitario", type: "real" },
      { name: "reservas", type: "json" },
      { name: "purchase_order", type: "text" },
      { name: "proveedor", type: "text" },
      { name: "proveedor_rfc", type: "text" },
      { name: "uuid_xml", type: "text" },
      { name: "articulos", type: "json" },
    ],
    indexes: [
      { name: "idx_inventory_reception_name", columns: ["name"] },
      { name: "idx_inventory_reception_active", columns: ["is_active"] },
    ],
  },
];
