import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { inventory_reception_pages } from "./inventory-reception.pages.ts";
import { inventory_reception_tables } from "./inventory-reception.tables.ts";

export const inventory_reception_module = define_module({
  resource: "inventory-reception",
  labels: {
    singular: "Recepciones",
    plural: "Recepciones",
    read: "Ver Recepciones",
    write: "Editar Recepciones",
  },
  routes: define_crud({
    resource: "inventory-reception",
    table: "inventory_reception",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "inventor",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      estado: { type: "string", search: true },
      purchase_order_nombre: { type: "string", search: true },
      purchase_order_id: { type: "string", search: true },
      producto_id: { type: "string", search: true },
      proveedor_nombre: { type: "string", search: true },
      referencia: { type: "string", search: true },
      fecha_esperada: { type: "string", search: true },
      total_esperado: { type: "number" },
      total_recibido: { type: "number" },
      documento_tipo: { type: "string", search: true },
      documento_id: { type: "string", search: true },
      documento_nombre: { type: "string", search: true },
      cantidad: { type: "number" },
      producto: { type: "string", search: true },
      producto_nombre: { type: "string", search: true },
      producto_codigo: { type: "string", search: true },
      codigo_proveedor: { type: "string", search: true },
      cantidad_esperada: { type: "number" },
      cantidad_recibida: { type: "number" },
      cantidad_acomodada: { type: "number" },
      costo_unitario: { type: "number" },
      reservas: { type: "json" },
      purchase_order: { type: "string", search: true },
      proveedor: { type: "string", search: true },
      proveedor_rfc: { type: "string", search: true },
      uuid_xml: { type: "string", search: true },
      articulos: { type: "json" },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: inventory_reception_tables,
  pages: inventory_reception_pages,
  menu: [],
});
