import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const inventory_movement_tables: KirletTableDecl[] = [
  {
    name: "inventory_movement",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "producto_nombre", type: "text" },
      { name: "producto_codigo", type: "text" },
      { name: "producto_id", type: "text" },
      { name: "ubicacion_origen_id", type: "text" },
      { name: "ubicacion_destino_id", type: "text" },
      { name: "tipo_movimiento", type: "text" },
      { name: "ubicacion_origen_nombre", type: "text" },
      { name: "ubicacion_destino_nombre", type: "text" },
      { name: "documento_tipo", type: "text" },
      { name: "documento_nombre", type: "text" },
      { name: "documento_referencia", type: "text" },
      { name: "cantidad", type: "real" },
      { name: "costo_unitario", type: "real" },
      { name: "stock_total_previo", type: "real" },
      { name: "stock_total_resultante", type: "real" },
      { name: "stock_apartado_previo", type: "real" },
      { name: "stock_apartado_resultante", type: "real" },
      { name: "stock_disponible_resultante", type: "real" },
      { name: "fecha_movimiento", type: "text" },
      { name: "producto", type: "text" },
      { name: "ubicacion_origen", type: "text" },
      { name: "ubicacion_destino", type: "text" },
      { name: "documento_id", type: "text" },
      { name: "documento_modelo", type: "text" },
      { name: "dedupe_key", type: "text" },
    ],
    indexes: [
      { name: "idx_inventory_movement_name", columns: ["name"] },
      { name: "idx_inventory_movement_active", columns: ["is_active"] },
    ],
  },
];
