import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { inventory_movement_pages } from "./inventory-movement.pages.ts";
import { inventory_movement_tables } from "./inventory-movement.tables.ts";

export const inventory_movement_module = define_module({
  resource: "inventory-movement",
  labels: {
    singular: "Movimientos de inventario",
    plural: "Movimientos de inventario",
    read: "Ver Movimientos de inventario",
    write: "Editar Movimientos de inventario",
  },
  routes: define_crud({
    resource: "inventory-movement",
    table: "inventory_movement",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "inventor",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      producto_nombre: { type: "string", search: true },
      producto_codigo: { type: "string", search: true },
      producto_id: { type: "string", search: true },
      ubicacion_origen_id: { type: "string", search: true },
      ubicacion_destino_id: { type: "string", search: true },
      tipo_movimiento: { type: "string", search: true },
      ubicacion_origen_nombre: { type: "string", search: true },
      ubicacion_destino_nombre: { type: "string", search: true },
      documento_tipo: { type: "string", search: true },
      documento_nombre: { type: "string", search: true },
      documento_referencia: { type: "string", search: true },
      cantidad: { type: "number" },
      costo_unitario: { type: "number" },
      stock_total_previo: { type: "number" },
      stock_total_resultante: { type: "number" },
      stock_apartado_previo: { type: "number" },
      stock_apartado_resultante: { type: "number" },
      stock_disponible_resultante: { type: "number" },
      fecha_movimiento: { type: "string", search: true },
      producto: { type: "string", search: true },
      ubicacion_origen: { type: "string", search: true },
      ubicacion_destino: { type: "string", search: true },
      documento_id: { type: "string", search: true },
      documento_modelo: { type: "string", search: true },
      dedupe_key: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: inventory_movement_tables,
  pages: inventory_movement_pages,
  menu: [],
});
