import { define_crud, define_module } from "@opus-perpetuus/imperium-core-kit";
import { inventory_cost_entry_pages } from "./inventory-cost-entry.pages.ts";
import { inventory_cost_entry_tables } from "./inventory-cost-entry.tables.ts";

export const inventory_cost_entry_module = define_module({
  resource: "inventory-cost-entry",
  labels: {
    singular: "Entradas de costo",
    plural: "Entradas de costo",
    read: "Ver Entradas de costo",
    write: "Editar Entradas de costo",
  },
  routes: define_crud({
    resource: "inventory-cost-entry",
    table: "inventory_cost_entry",
    soft_delete: true,
    soft_delete_field: "is_active",
    history: true,
    default_sort: "name:asc",
    id_prefix: "inventor",
    fields: {
      name: { type: "string", required: true, search: true },
      description: { type: "string", search: true },
      is_active: { type: "boolean" },
      state: { type: "string" },
      ref: { type: "string", search: true },
      search_field: { type: "string", search: true },
      created_by: { type: "string" },
      custom_data: { type: "json" },
      payload: { type: "json" },
      receipt_key: { type: "string", search: true },
      recepcion_referencia: { type: "string", search: true },
      orden_compra_nombre: { type: "string", search: true },
      orden_compra_folio: { type: "number" },
      orden_compra_referencia: { type: "string", search: true },
      producto_nombre: { type: "string", search: true },
      producto_codigo: { type: "string", search: true },
      proveedor_nombre: { type: "string", search: true },
      tipo_origen: { type: "string", search: true },
      cantidad: { type: "number" },
      costo_unitario: { type: "number" },
      costo_total: { type: "number" },
      stock_previo: { type: "number" },
      stock_resultante: { type: "number" },
      costo_promedio_resultante: { type: "number" },
      fecha_entrada: { type: "string", search: true },
      orden_compra: { type: "string", search: true },
      producto: { type: "string", search: true },
      proveedor: { type: "string", search: true },
      proveedor_rfc: { type: "string", search: true },
    },
    options_map: { value: "id", label: "name" },
  }),
  tables: inventory_cost_entry_tables,
  pages: inventory_cost_entry_pages,
  menu: [],
});
