import type { KirletTableDecl } from "@opus-perpetuus/imperium-core-kit";

export const inventory_cost_entry_tables: KirletTableDecl[] = [
  {
    name: "inventory_cost_entry",
    columns: [
      { name: "id", type: "text", primaryKey: true },
      { name: "name", type: "text", notNull: true },
      { name: "description", type: "text" },
      { name: "is_active", type: "boolean", notNull: true, default: true },
      { name: "state", type: "text" },
      { name: "ref", type: "text", unique: true },
      { name: "search_field", type: "text" },
      { name: "created_by", type: "text" },
      { name: "custom_data", type: "json" },
      { name: "payload", type: "json" },
      { name: "created_at", type: "text", notNull: true },
      { name: "updated_at", type: "text", notNull: true },
      { name: "receipt_key", type: "text" },
      { name: "recepcion_referencia", type: "text" },
      { name: "orden_compra_nombre", type: "text" },
      { name: "orden_compra_folio", type: "real" },
      { name: "orden_compra_referencia", type: "text" },
      { name: "producto_nombre", type: "text" },
      { name: "producto_codigo", type: "text" },
      { name: "proveedor_nombre", type: "text" },
      { name: "tipo_origen", type: "text" },
      { name: "cantidad", type: "real" },
      { name: "costo_unitario", type: "real" },
      { name: "costo_total", type: "real" },
      { name: "stock_previo", type: "real" },
      { name: "stock_resultante", type: "real" },
      { name: "costo_promedio_resultante", type: "real" },
      { name: "fecha_entrada", type: "text" },
      { name: "orden_compra", type: "text" },
      { name: "producto", type: "text" },
      { name: "proveedor", type: "text" },
      { name: "proveedor_rfc", type: "text" },
    ],
    indexes: [
      { name: "idx_inventory_cost_entry_name", columns: ["name"] },
      { name: "idx_inventory_cost_entry_active", columns: ["is_active"] },
    ],
  },
];
